# Generated by Django 5.0.6 on 2024-07-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='pieces',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
