# Generated by Django 5.0.6 on 2024-07-05 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_variant_pieces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(default='cabinate handles', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='color_finish_middle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='color_finish_middle', to='base.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(default='aluminium', max_length=20),
        ),
        migrations.AlterField(
            model_name='variant',
            name='color_finish_down',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='color_finish_down', to='base.color'),
        ),
    ]
