# Generated by Django 5.0.6 on 2024-07-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_product_name_product_product_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
