# Generated by Django 5.0.6 on 2024-07-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_variant_image_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='price_customer',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='variant',
            name='price_retailer',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
