# Generated by Django 5.0.6 on 2024-07-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_variant_price_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='size_inch',
            field=models.CharField(blank=True, choices=[('4', '4"'), ('6', '6"'), ('8', '8"'), ('10', '10"'), ('12', '12"'), ('14', '14"'), ('16', '16"'), ('18', '18"'), ('24', '24"'), ('36', '36"'), ('48', '48"')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='size_mm',
            field=models.CharField(blank=True, choices=[('96', '96mm'), ('128', '128mm'), ('160', '160mm'), ('224', '224mm'), ('256', '256mm'), ('288', '288mm'), ('416', '416mm'), ('576', '576mm'), ('864', '864mm'), ('1184', '1184mm')], max_length=5, null=True),
        ),
    ]
